//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.4016
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TexasHoldemCalculator.Core.Resource
{


    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    internal class HoldemStringResource
    {

        private static global::System.Resources.ResourceManager resourceMan;

        private static global::System.Globalization.CultureInfo resourceCulture;

        internal HoldemStringResource()
        {
        }

        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager
        {
            get
            {
                if (object.ReferenceEquals(resourceMan, null))
                {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Holdem.Resource.HoldemResource", typeof(HoldemResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }

        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture
        {
            get
            {
                return resourceCulture;
            }
            set
            {
                resourceCulture = value;
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Card Image File is missing!.
        /// </summary>
        internal static string Exception_CardMissing
        {
            get
            {
                return ResourceManager.GetString("Exception_CardMissing", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Configuration File is missing!.
        /// </summary>
        internal static string Exception_ConfigurationMissing
        {
            get
            {
                return ResourceManager.GetString("Exception_ConfigurationMissing", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Higher vs. Lower.
        /// </summary>
        internal static string Hand0_Description_PocketPairMatchup
        {
            get
            {
                return ResourceManager.GetString("Hand0_Description_PocketPairMatchup", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to 4.09:1.
        /// </summary>
        internal static string Hand0_Odds_PocketPairMatchup
        {
            get
            {
                return ResourceManager.GetString("Hand0_Odds_PocketPairMatchup", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to 80.3% vs. 19.7%.
        /// </summary>
        internal static string Hand0_Percent_PocketPairMatchup
        {
            get
            {
                return ResourceManager.GetString("Hand0_Percent_PocketPairMatchup", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Pair vs. Two Over.
        /// </summary>
        internal static string Hand1_Description_PocketPairMatchup
        {
            get
            {
                return ResourceManager.GetString("Hand1_Description_PocketPairMatchup", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to 1.23:1.
        /// </summary>
        internal static string Hand1_Odds_PocketPairMatchup
        {
            get
            {
                return ResourceManager.GetString("Hand1_Odds_PocketPairMatchup", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to 55.1% vs. 44.9%.
        /// </summary>
        internal static string Hand1_Percent_PocketPairMatchup
        {
            get
            {
                return ResourceManager.GetString("Hand1_Percent_PocketPairMatchup", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Pair vs. Two Under.
        /// </summary>
        internal static string Hand2_Description_PocketPairMatchup
        {
            get
            {
                return ResourceManager.GetString("Hand2_Description_PocketPairMatchup", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to 4.77:1.
        /// </summary>
        internal static string Hand2_Odds_PocketPairMatchup
        {
            get
            {
                return ResourceManager.GetString("Hand2_Odds_PocketPairMatchup", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to 82.7% vs. 17.3%.
        /// </summary>
        internal static string Hand2_Percent_PocketPairMatchup
        {
            get
            {
                return ResourceManager.GetString("Hand2_Percent_PocketPairMatchup", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Pair vs. Over/Under.
        /// </summary>
        internal static string Hand3_Description_PocketPairMatchup
        {
            get
            {
                return ResourceManager.GetString("Hand3_Description_PocketPairMatchup", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to 2.50:1.
        /// </summary>
        internal static string Hand3_Odds_PocketPairMatchup
        {
            get
            {
                return ResourceManager.GetString("Hand3_Odds_PocketPairMatchup", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to 71.4% vs. 28.6%.
        /// </summary>
        internal static string Hand3_Percent_PocketPairMatchup
        {
            get
            {
                return ResourceManager.GetString("Hand3_Percent_PocketPairMatchup", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Two Over vs. Two Under.
        /// </summary>
        internal static string Hand4_Description_PocketPairMatchup
        {
            get
            {
                return ResourceManager.GetString("Hand4_Description_PocketPairMatchup", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to 1.70:1.
        /// </summary>
        internal static string Hand4_Odds_PocketPairMatchup
        {
            get
            {
                return ResourceManager.GetString("Hand4_Odds_PocketPairMatchup", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to 62.9% vs. 37.1%.
        /// </summary>
        internal static string Hand4_Percent_PocketPairMatchup
        {
            get
            {
                return ResourceManager.GetString("Hand4_Percent_PocketPairMatchup", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Higher/Lower vs. Middle.
        /// </summary>
        internal static string Hand5_Description_PocketPairMatchup
        {
            get
            {
                return ResourceManager.GetString("Hand5_Description_PocketPairMatchup", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to 1.27:1.
        /// </summary>
        internal static string Hand5_Odds_PocketPairMatchup
        {
            get
            {
                return ResourceManager.GetString("Hand5_Odds_PocketPairMatchup", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to 55.9% vs. 44.1%.
        /// </summary>
        internal static string Hand5_Percent_PocketPairMatchup
        {
            get
            {
                return ResourceManager.GetString("Hand5_Percent_PocketPairMatchup", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to High/3rd High vs. Low/3rd Low.
        /// </summary>
        internal static string Hand6_Description_PocketPairMatchup
        {
            get
            {
                return ResourceManager.GetString("Hand6_Description_PocketPairMatchup", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to 1.73:1.
        /// </summary>
        internal static string Hand6_Odds_PocketPairMatchup
        {
            get
            {
                return ResourceManager.GetString("Hand6_Odds_PocketPairMatchup", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to 63.3% vs. 36.7%.
        /// </summary>
        internal static string Hand6_Percent_PocketPairMatchup
        {
            get
            {
                return ResourceManager.GetString("Hand6_Percent_PocketPairMatchup", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Dominated Same Lower.
        /// </summary>
        internal static string Hand7_Description_PocketPairMatchup
        {
            get
            {
                return ResourceManager.GetString("Hand7_Description_PocketPairMatchup", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to 2.74:1.
        /// </summary>
        internal static string Hand7_Odds_PocketPairMatchup
        {
            get
            {
                return ResourceManager.GetString("Hand7_Odds_PocketPairMatchup", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to 73.3% vs. 26.7%.
        /// </summary>
        internal static string Hand7_Percent_PocketPairMatchup
        {
            get
            {
                return ResourceManager.GetString("Hand7_Percent_PocketPairMatchup", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Dominated Same Higher.
        /// </summary>
        internal static string Hand8_Description_PocketPairMatchup
        {
            get
            {
                return ResourceManager.GetString("Hand8_Description_PocketPairMatchup", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to 2:1.
        /// </summary>
        internal static string Hand8_Odds_PocketPairMatchup
        {
            get
            {
                return ResourceManager.GetString("Hand8_Odds_PocketPairMatchup", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to 67% vs. 33%.
        /// </summary>
        internal static string Hand8_Percent_PocketPairMatchup
        {
            get
            {
                return ResourceManager.GetString("Hand8_Percent_PocketPairMatchup", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        internal static string Holdem_Calculator_Description
        {
            get
            {
                return ResourceManager.GetString("Holdem_Calculator_Description", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Percent.
        /// </summary>
        internal static string Holdem_Calculator_Percent
        {
            get
            {
                return ResourceManager.GetString("Holdem_Calculator_Percent", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Texas Holdem Calculator 1.5.0.0 Copyright © mkrain 2008.
        /// </summary>
        internal static string HoldemCalculator_Creator
        {
            get
            {
                return ResourceManager.GetString("HoldemCalculator_Creator", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to mkrain@hotmail.com.
        /// </summary>
        internal static string HoldemCalculator_Email
        {
            get
            {
                return ResourceManager.GetString("HoldemCalculator_Email", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to https://sourceforge.net/projects/texasholdemcalc/.
        /// </summary>
        internal static string HoldemCalculator_URL
        {
            get
            {
                return ResourceManager.GetString("HoldemCalculator_URL", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Item selected is not valid..
        /// </summary>
        internal static string THC_File_Load_Error_Message
        {
            get
            {
                return ResourceManager.GetString("THC_File_Load_Error_Message", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to File Load Error.
        /// </summary>
        internal static string THC_File_Load_Error_Title
        {
            get
            {
                return ResourceManager.GetString("THC_File_Load_Error_Title", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Loading could take a while with many hands per file..
        /// </summary>
        internal static string THC_File_Load_Info_Message
        {
            get
            {
                return ResourceManager.GetString("THC_File_Load_Info_Message", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Loading Hand History.
        /// </summary>
        internal static string THC_File_Load_Info_Title
        {
            get
            {
                return ResourceManager.GetString("THC_File_Load_Info_Title", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to mailto:mkrain@hotmail.com?subject=texasholdemcalculator.
        /// </summary>
        internal static string THC_General_MailTo
        {
            get
            {
                return ResourceManager.GetString("THC_General_MailTo", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Date/Time:.
        /// </summary>
        internal static string THC_History_Date_Time
        {
            get
            {
                return ResourceManager.GetString("THC_History_Date_Time", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Directory missing:.
        /// </summary>
        internal static string THC_History_Directory_Missing
        {
            get
            {
                return ResourceManager.GetString("THC_History_Directory_Missing", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Game Id:.
        /// </summary>
        internal static string THC_History_Game_Id
        {
            get
            {
                return ResourceManager.GetString("THC_History_Game_Id", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to 0 records found in the file..
        /// </summary>
        internal static string THC_History_Zero_Records_Message
        {
            get
            {
                return ResourceManager.GetString("THC_History_Zero_Records_Message", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to No Hand History Found.
        /// </summary>
        internal static string THC_History_Zero_Records_Title
        {
            get
            {
                return ResourceManager.GetString("THC_History_Zero_Records_Title", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Texas Holdem Calculator.
        /// </summary>
        internal static string THC_Splash_App_Name
        {
            get
            {
                return ResourceManager.GetString("THC_Splash_App_Name", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to HoldemSplashAnimation.
        /// </summary>
        internal static string THC_Splash_App_Title
        {
            get
            {
                return ResourceManager.GetString("THC_Splash_App_Title", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Loading please wait....
        /// </summary>
        internal static string THC_Splash_Loading_Message
        {
            get
            {
                return ResourceManager.GetString("THC_Splash_Loading_Message", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Amount won [All]:.
        /// </summary>
        internal static string THC_Stat_Amount_Won_All
        {
            get
            {
                return ResourceManager.GetString("THC_Stat_Amount_Won_All", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Amount won [Game]:.
        /// </summary>
        internal static string THC_Stat_Amount_Won_Game
        {
            get
            {
                return ResourceManager.GetString("THC_Stat_Amount_Won_Game", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Average won per hand [All]:.
        /// </summary>
        internal static string THC_Stat_Avg_Won_Per_Hand_All
        {
            get
            {
                return ResourceManager.GetString("THC_Stat_Avg_Won_Per_Hand_All", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Average won per hand [Game]:.
        /// </summary>
        internal static string THC_Stat_Avg_Won_Per_Hand_Game
        {
            get
            {
                return ResourceManager.GetString("THC_Stat_Avg_Won_Per_Hand_Game", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Average won per hand [Won]:.
        /// </summary>
        internal static string THC_Stat_Avg_Won_Per_Hand_Won
        {
            get
            {
                return ResourceManager.GetString("THC_Stat_Avg_Won_Per_Hand_Won", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Hands won [All]:.
        /// </summary>
        internal static string THC_Stat_Hand_Won_All
        {
            get
            {
                return ResourceManager.GetString("THC_Stat_Hand_Won_All", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Hands won [Game]:.
        /// </summary>
        internal static string THC_Stat_Hand_Won_Game
        {
            get
            {
                return ResourceManager.GetString("THC_Stat_Hand_Won_Game", resourceCulture);
            }
        }
    }
}
